### ISSUE TITLE
Can transformation target size be limited

### ISSUE THREAD

**Issue by igorbga** [Alfresco/alfresco-transform-core#497]
This is not a bug but a feature request/suggestion.

I have observed that in an installation for Alfresco 7.1 with the "aio" transformer the transformation to text of one PDF file created a 53G text file. I think the source PDF is merely around 20MB but to be honest is a running production server and couldn't identify the source file 100% sure.

Due to that i've seen "no space left on device" exceptions in the transformers log. Analyzing the exception stack it seems quite obvius that in this case it was the Tika transformer.

I know that the max source file bytes can be set in transformation configuration, so more or less I can control how much space teh source of a transformation can take. But what about the target ?

AFAIK SOLR is limited to only index the first X words of any sent text document so if our use case for the text transformation is just indexation it would be great if the transformers could somehow be limited to a maximum file size.

Does it make any sense ? Is it already possible in some way ?

**Comment by montgolfiere** [comment]
@igorbga Thanks for the feedback. 

Unfortunately that sounds like a bug in Tika causing an invalid transform. For reference, can you please confirm the exact version of T-Core (and hence Tika) ?

As an aside: it should be noted that we're also in the process of updating Tika 2.1.0 (and potentially Tika 2.2.1) in the near future. In the even that you can identify the offending source file (with repeatable test case) then you could also check to see if this is a known issue that may have been fixed in more recent versions of Tika.

Such a potential setting would depend on the capabilities for each specific transformer (whether Java-based such as Tika or other external processes) being able to accept such a limit and cut-off a transformation mid-stream.

This is one of many reason that we moved to out-of-process transforms (also recommended by Tika team, eg. https://issues.apache.org/jira/browse/TIKA-2952). We also highly recommend that the transform engine(s) run on separate transformation tier (server) from the core content repository tier (server).
